### ISSUE TITLE
Перейти на Json, добавить параметры к карточкам

### ISSUE THREAD

**Issue by Algorithm0** [Greggot/ggis-panopticon#17]
У нас теперь стало довольно актуально стало создание карточек исследования.
Есть и другие вопросы, которые классно было бы передавать карточкам.
Предлагаю всё же сменить `tasks.txt` на `tasks.json`

~~~json5
{
  "US-EN": {
    "0.148": [
      {
        "name": "Сделать дичь",
        "type": "TD", //Может отсутствовать (TS по умолчанию)
        "size": 8 //Может отсутствовать (16 по умолчанию)
      },
      {
        "name": "Исследовать дичь",
        "type": "TS"
      }
    ],
    "97.7": [
      {
        "name": "Сделать еще дичь"
      }
    ]
  },
  "BUG": []
}
~~~ 

Могу помочь в реализации, если автор меня проконсультирует

**Comment by Greggot** [comment]
Ну тк обновление есть с параметрами. У тебя есть шаблон, в котором говоришь, куда кастовать карточки, по сколько часов туда по дефлоту писать. Модифицировать JSON каждый раз, когда тебе просто нужно создать таких же задач, просто  сдругими именами -- как-то куда сложнее, чем записать с табами в текстовый файлик

**Comment by Algorithm0** [comment]
Может создать скрипт, который в консольном режиме будет опрашивать пользователя? Он автоматом создаст такой json. Позже его можно вручную отредактировать или снова вызвать скрипт по созданию конфигурации.
Постоянно лезть в исходники - такое себе.

**Comment by Greggot** [comment]
Ну тк в текущей версии ты меняешь или создаешь конфиг только тогда, когда нужно на новую борду или колонку кастовать карточки. Для этого нужно заполнить около 3-х ID, которые неизвестны, пока ты не посмотришь консоль в браузере -- т.е. чтобы сделать через консоль опрос "Куда создавать карточки", нужно будет дописать опрос всех борд и колонок по именам

Крч, можешь это в отдельной ветке попробовать сделать, я тебя добавлю в разрабы. Если получится норм -- прильем

**Comment by Algorithm0** [comment]
Реализовано
